### ISSUE TITLE
Meta Optimization

### ISSUE THREAD

**Issue by ylsaker** [cyang-cityu/MetaCorrection#8]
Hi, 
     Thank you for your awesome paper.I'm studying UDA based on your work.
     In meta optimization step, Noisy Transition Matrix has not been used, so it is not in the graph. How to calculate grads about T?

**Comment by supercheney** [comment]
Sorry for my late reply. In the virtual optimization step, the Noisy Transition Matrix is used to calculate the loss. Since the virtual optimization step and meta optimization step are based on the same meta net, grads of T can be calculated by the chain rule. You can follow Meta-Weight-Net to understand it better.

**Comment by cyang-cityu** [comment]
Sorry for my late reply. In the virtual optimization step, the Noisy Transition Matrix is used to calculate the loss. Since the virtual optimization step and meta optimization step are based on the same meta net, grads of T can be calculated by the chain rule. You can follow Meta-Weight-Net to understand it better.
